### ISSUE TITLE
Linux wifi setup

### ISSUE THREAD

**Issue by davidwibowo** [Ennovar/triage#1]
How to set up Wifi in linux
- check if wifi working
- driver needed

**Comment by hoangdangninh** [comment]
Feel happy now @davidwibowo ? Better say thanks to @jerekshoe for providing you a password on Ennovar network :)

**Comment by davidwibowo** [comment]
Problem:
all driver is there but not trigger
solution:
use nmcli
nmcli device wifi list

Thanks @hoangdangninh
