### ISSUE TITLE
HTTPS image not showing up on Android

### ISSUE THREAD

**Issue by mcrice123** [Ennovar/triage#10]
We solved the issue I posted earlier about images not showing on IOS for my team's mobile app. We changed the image addresses from HTTP to HTTPS and the images show up. 

Now my team member tells me the images don't show on Android. 

[face palm]

Based off of the few resources on the internet that actually come up when I search "android emulator not showing https images", it looks like there could be issues of there being a mix of images with http or https. However, we're not _displaying_ http images. We still have http images stored in objects accessed by the app, but they are never to be used because the https images replace them. I was told we just couldn't delete the http images, though, and I don't know if that's what's causing the issue. 

Any thoughts as to how to fix this or what the problem is?

**Comment by mcrice123** [comment]
Heh...funny thing. The same team member says that the HTTPS images show up on Android just fine now.

🤣 

Thanks everyone who tried to help!

**Comment by hoangdangninh** [comment]
Glad you have had it resolved 👍
