### ISSUE TITLE
HTTP uri not working on IOS

### ISSUE THREAD

**Issue by mcrice123** [Ennovar/triage#3]
I have a React Native project that is supposed to display an image on a certain component. When I last checked how it worked on Android emulator, it worked as expected. However, on the IOS simulator, no image appears and it checks to see if no image is available before either showing the image or showing text that it is not available. It does neither, just shows white space.

I researched the issue and discovered that IOS does not generally show images with 'http' in the uri and that it would need to be changed so that it is 'https'. My problem is that I don't know how the uri is generated to begin with. The user uploads the image and an api call is made to create a new object that includes the image as one of its attributes. The uri of this image is accessible through another call to the same api. 

It appears that in order to render the image in IOS, I have to change the uri of all the images AND I need to know how to change the backend generation of uris. My team's backend person won't be here until next week, so any input about solving this issue is appreciated.

**Comment by jerekshoe** [comment]
Just out of curiosity does the image have any styling? If so could you post the styles you are using on it

**Comment by mcrice123** [comment]
@jerekshoe This should be it.
`image: {
		width: '100%',
		height: 300,
	},`

**Comment by jerekshoe** [comment]
Ok.. just for future reference, using padding with images has different behavior on ios and android. That doesnt appear to be your issues so, you just need to have the backend where the images are stored use https instead of http.. your backend person should be able to enable SSL on the server then you will be fine.

**Comment by mcrice123** [comment]
Thanks. I'll wait for my backend person to return to solve this.

**Comment by hoangdangninh** [comment]
@mcrice123 : is she/he on github? we can let her/him collaborate on this

**Comment by mcrice123** [comment]
@hoangdangninh It's Shruthi. Don't know if she is.

**Comment by hoangdangninh** [comment]
@Shruthi2702 is it you?  :crossed_fingers:

**Comment by Shruthi2702** [comment]
@hoangdangninh Yeah that is me

**Comment by mcrice123** [comment]
@Shruthi2702 added another parameter to the object from which the image url is stored and this new parameter contains the new https address for the image (could not modify existing parameter). Then I looked back at the code and edited it so that it accesses this new parameter. Reloaded the simulator and the image shows up as needed. 🎉
