### ISSUE TITLE
API function shows on localhost, but not when pushed to Heroku

### ISSUE THREAD

**Issue by mcrice123** [Ennovar/triage#6]
I'm working on a website created using React and Redux. It makes various API calls and works as expected when run on localhost. When I stop the server and push the current branch to Heroku (and I double-checked, it's NOT master, so I had to specify my current branch as the branch to push), certain functions do not show up in bundle.js, where they did when run on localhost. All the api functions show up on localhost, but not all of them show up on Heroku. As a result, the data that shows up when those missing functions are called never appear on Heroku because they are never called. 

(Also: API is listed under dependencies, not devdependencies, in package.json. In case you were wondering.)

Does anyone know why this happens? ~~I'm guessing maybe it has something to do with Redux sagas.~~ Still looking into it--couldn't find any answered issues written up on the internet.

**Comment by AustinMCrane** [comment]
did you run npm run build before pushing it?

**Comment by mcrice123** [comment]
@AustinMCrane No. What does that do?

**Comment by mcrice123** [comment]
I'm thinking that the problem lies on a devdependency that is needed as simply a dependency in order for those functions to work on Heroku. Here are my devdependencies and dependencies. 
`  "devDependencies": {
    "babel-core": "^6.24.1",
    "babel-eslint": "^7.2.3",
    "babel-jest": "^20.0.3",
    "babel-loader": "^7.1.1",
    "babel-polyfill": "^6.23.0",
    "babel-preset-es2015": "^6.24.1",
    "babel-preset-react": "^6.24.1",
    "babel-preset-stage-2": "^6.24.1",
    "css-loader": "^0.28.1",
    "enzyme": "^2.8.2",
    "esdoc": "^0.5.2",
    "eslint": "^3.19.0",
    "eslint-config-airbnb": "^15.0.1",
    "eslint-loader": "^1.7.1",
    "eslint-plugin-import": "^2.2.0",
    "eslint-plugin-jsx-a11y": "^5.0.3",
    "eslint-plugin-react": "^7.0.1",
    "file-loader": "^0.11.1",
    "html-webpack-plugin": "^2.28.0",
    "husky": "^0.13.3",
    "identity-obj-proxy": "^3.0.0",
    "image-webpack-loader": "^3.3.1",
    "jest": "^20.0.1",
    "lint-staged": "^3.4.2",
    "moxios": "^0.4.0",
    "pui-react-svg": "^8.3.1",
    "react-svg-loader": "^1.1.1",
    "react-test-renderer": "^15.5.4",
    "redux-devtools": "^3.4.0",
    "redux-devtools-dock-monitor": "^1.1.2",
    "redux-devtools-log-monitor": "^1.3.0",
    "sinon": "^2.2.0",
    "style-loader": "^0.17.0",
    "webpack": "^2.6.1",
    "webpack-dev-server": "^2.4.5"
  },
  "dependencies": {
    "babel-loader": "^7.1.1",
    "babel-polyfill": "^6.23.0",
    "babel-preset-es2015": "^6.24.1",
    "babel-preset-react": "^6.24.1",
    "bike_app_api_client": "git+https://playerone:ennovaristhebest@gitlab.com/thesquad/bike_app_api_client.git",
    "clipboard": "^1.7.1",
    "exports-loader": "^0.6.4",
    "history": "^4.6.1",
    "imports-loader": "^0.7.1",
    "lodash": "^4.17.4",
    "pngquant": "^1.3.0",
    "prop-types": "^15.5.10",
    "pui-react-copy-to-clipboard": "^8.3.1",
    "pui-react-iconography": "^8.3.1",
    "pui-react-svg": "^8.3.1",
    "react": "^15.5.4",
    "react-clipboard": "^1.3.1",
    "react-dom": "^15.5.4",
    "react-dropzone": "^3.13.3",
    "react-file-download": "^0.3.4",
    "react-google-maps": "^6.3.0",
    "react-loader-advanced": "^1.6.0",
    "react-redux": "^5.0.4",
    "react-router": "^4.1.1",
    "react-router-dom": "^4.1.1",
    "react-router-redux": "^5.0.0-alpha.6",
    "react-spinkit": "^3.0.0",
    "react-svg-loader": "^1.1.1",
    "redux": "^3.6.0",
    "redux-saga": "^0.15.3",
    "regenerator-runtime": "^0.10.5",
    "styled-components": "^2.0.1"
  }

**Comment by mcrice123** [comment]
I suspect I might not have pushed to Heroku correctly. I spotted a bug in what's showing in Heroku that I KNOW was fixed in the branch I was trying to push. The fix is still in that branch.

This was the command I used to push the branch:
git push heroku button-component:master

'button-component' is the name of the branch I wanted to push. I checked 'master' to see if it corresponds to what I'm seeing on Heroku, but it's missing the 'Manage Keys' option altogether, indicating that when the option was added to 'button-component', it was never merged to master, but it was pushed to Heroku. It was there prior to my pushes to Heroku.

**Comment by mcrice123** [comment]
Just tried updating my remote url for heroku based on documentation here: https://devcenter.heroku.com/articles/git

Now git remote -v shows remote for heroku as same address but starting with 'https://'.

git push heroku button-component:master

Changes from button-component _still_ not applying!

**Comment by mcrice123** [comment]
Found the solution!

Turns out I didn't call 'npm run build' when I had something to commit. Therefore 'bundle.js' was not updated and that's what Heroku needed to display new changes. 

[make changes to code]
npm run build
git add .
git commit -m "message"
git push heroku button-component:master

Now it works!
Thanks @jerekshoe for finding the solution!
